# Generated by Django 2.0.1 on 2018-01-27 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('factura_proveedor', models.CharField(max_length=20)),
                ('fecha_gasto', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=20)),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Iva')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Proveedor'),
        ),
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
